sever:
  port: 8080

spring:
  datasource:
    #通用数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bunny?charset=utf8mb4&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  #jpa
  jpa:
    database: mysql
    #配置在日志中打印出执行的 SQL 语句信息
    show-sql: true
    #配置指明在程序启动的时候要对创建实体类对应表的操作
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
        #在建表的时候，将默认的存储引擎切换为 InnoDB
        dialect : org.hibernate.dialect.MySQL5Dialect
logging:
  config: classpath:log4j2.xml